name: Seen
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.1+1
  flutter_svg: ^2.0.10+1
  cherry_toast:
  google_maps_flutter_web: ^0.5.10
  intl: ^0.18.0
  shimmer: ^3.0.0
  google_fonts: ^5.1.0
  get_it: ^7.2.0
  image_picker: ^1.0.0
  dio: ^5.3.2
  pinput:
  flutter_spinkit: ^5.2.0
  dropdown_button2:
  flutter_feather_icons: ^2.0.0+1
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  flutter_lints: ^2.0.0
  stacked_generator: ^1.3.3



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/stickers/
    - assets/market/

